--local assetDir = "assets/"
--  aGraphics = assetDir.."art/"
--    aPaddle = aGraphics.."paddle.gif"
--    aBall = aGraphics.."ball.gif"
--  aSounds = assetDir.."audio/"
--    aPong = aSounds.."pong.ogg"
--    aLoss = aSounds.."loss.ogg"

local codeDir = "scripts/"
  cEntities = codeDir.."entities/"
    cPaddle = require(cEntities.."paddle")
    cBall = require(cEntities.."ball")
  cLogic = codeDir.."logic/"
    cControls = require(cLogic.."controls")
    cDraw = require(cLogic.."draw")
    cCollision = require(cLogic.."collision")
  cField = require(codeDir.."field")
  cMainMenu = require(codeDir.."mainmenu")
  cInit = require(codeDir.."init")
  cG = require(codeDir.."global")
  cButton = require(codeDir.."button")
  cBtnActions = require(codeDir.."btnActions")